### ISSUE TITLE
Gooey compatibility

### ISSUE THREAD

**Issue by UplinkPhobia** [casperdcl/argopt#10]
I found this repository through https://github.com/chriskiehl/Gooey/issues/4
I was wondering, is argopt compatible with gooey in the current state?

Thanks in advance

**Comment by casperdcl** [comment]
Related to https://github.com/chriskiehl/Gooey/pull/158 but haven't tested recently

**Comment by UplinkPhobia** [comment]
From what I've tested so far, it seems to mostly work, except for a bug when combining some arguments in the docstring.
`bug.py <x>` and `bug.py [--option]` work, but `bug.py <x> [--option]` will crash, with a
`bug.py: error: unrecognized arguments: <value_of_x>`

It seems to be independent from gooey though

**Comment by casperdcl** [comment]
Just tried (using current [`devel`](https://github.com/casperdcl/argopt/tree/devel)). `python examples/demo_advanced.py --with-gooey` seems to work fine.

**Comment by casperdcl** [comment]
About option ordering, this also works:

```bash
python examples/demo_basic.py arg1 --force
```

**Comment by UplinkPhobia** [comment]
I wasn't using the devel branch, after switching it seems to be working. I'll try to use it and see if I encouter any issue.
Thank you for the help

**Comment by casperdcl** [comment]
just released a new version (0.6.1) so you don't need to use devel :)

**Comment by UplinkPhobia** [comment]
Thanks ^^
